version: "3.2"
services:
  dev:
    container_name: node-template
    image: paritytech/ci-linux:production
    working_dir: /var/www/node-template
    ports:
      - "9944:9944"
    volumes:
      - .:/var/www/node-template
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "rustup install nightly-2023-03-13-x86_64-unknown-linux-gnu && rustup default nightly-2023-03-13-x86_64-unknown-linux-gnu && rustup target add wasm32-unknown-unknown && cargo build --release && ./target/release/node-template --dev --ws-external"